# frozen_string_literal: true

module UsersHelper
  def skills
    ['ADO.NET',
     'AI Programming',
     'ASP / ASP.NET',
     'AWS',
     'ActionScript',
     'Ada',
     'Alice',
     'Assembly Language',
     'AutoLISP',
     'Awk',
     'BASH',
     'Backbone.js',
     'Basic',
     'Blockchain',
     'Bootstrap',
     'C',
     'C Shell',
     'C++',
     'CGI',
     'COBOL',
     'CORBA',
     'CSS / CSS3',
     'C#',
     'Clojure',
     'Cocoa',
     'CoffeeScript',
     'Delphi',
     'Drupal',
     'Elixir',
     'Erlang',
     'Extreme Programming',
     'Pair Programming',
     'Functional JavaScript',
     'Functional Programming',
     'Git',
     'Go',
     'HTML',
     'HTML5',
     'Haskell',
     'JSON',
     'Java',
     'Javascript',
     'jQuery',
     'Linux Programming',
     'Lisp',
     'MATLAB',
     'MS-DOS',
     'MS-Windows',
     'Machine Learning',
     'Mercurial',
     'MySQL',
     'Network Programming',
     'Node.js',
     'Objective-C',
     'PHP',
     'Pascal',
     'Perl',
     'Phoenix',
     'PostgreSQL',
     'Project Management',
     'Python',
     'R',
     'Raspberry Pi',
     'RegEx',
     'Ruby',
     'Rails',
     'SAS',
     'SQL',
     'SQLite',
     'Scala',
     'Scratch',
     'Simula',
     'Smalltalk',
     'Swift',
     'LaTeX',
     'UNIX Programming',
     'Ubuntu',
     'VB.NET']
  end
end
